// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/retr0h/agentpack/internal/remove (interfaces: Registry)
//
// Generated by this command:
//
//	mockgen -destination=registry.gen.go -package=mocks github.com/retr0h/agentpack/internal/remove Registry
//
// NOTE: Save method added manually to match the updated Registry interface.

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	registry "github.com/retr0h/agentpack/internal/registry"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistry is a mock of Registry interface.
type MockRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryMockRecorder
	isgomock struct{}
}

// MockRegistryMockRecorder is the mock recorder for MockRegistry.
type MockRegistryMockRecorder struct {
	mock *MockRegistry
}

// NewMockRegistry creates a new mock instance.
func NewMockRegistry(ctrl *gomock.Controller) *MockRegistry {
	mock := &MockRegistry{ctrl: ctrl}
	mock.recorder = &MockRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistry) EXPECT() *MockRegistryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockRegistry) Load(name string) (*registry.PackageManifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", name)
	ret0, _ := ret[0].(*registry.PackageManifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockRegistryMockRecorder) Load(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockRegistry)(nil).Load), name)
}

// Remove mocks base method.
func (m *MockRegistry) Remove(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRegistryMockRecorder) Remove(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRegistry)(nil).Remove), name)
}

// Save mocks base method.
func (m *MockRegistry) Save(manifest *registry.PackageManifest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", manifest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRegistryMockRecorder) Save(manifest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRegistry)(nil).Save), manifest)
}
