// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/retr0h/agentpack/pkg/outdated (interfaces: RemoteChecker)
//
// Generated by this command:
//
//	mockgen -destination=remote_checker.gen.go -package=mocks github.com/retr0h/agentpack/pkg/outdated RemoteChecker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRemoteChecker is a mock of RemoteChecker interface.
type MockRemoteChecker struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteCheckerMockRecorder
	isgomock struct{}
}

// MockRemoteCheckerMockRecorder is the mock recorder for MockRemoteChecker.
type MockRemoteCheckerMockRecorder struct {
	mock *MockRemoteChecker
}

// NewMockRemoteChecker creates a new mock instance.
func NewMockRemoteChecker(ctrl *gomock.Controller) *MockRemoteChecker {
	mock := &MockRemoteChecker{ctrl: ctrl}
	mock.recorder = &MockRemoteCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteChecker) EXPECT() *MockRemoteCheckerMockRecorder {
	return m.recorder
}

// LsRemote mocks base method.
func (m *MockRemoteChecker) LsRemote(ctx context.Context, source string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LsRemote", ctx, source)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LsRemote indicates an expected call of LsRemote.
func (mr *MockRemoteCheckerMockRecorder) LsRemote(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LsRemote", reflect.TypeOf((*MockRemoteChecker)(nil).LsRemote), ctx, source)
}
