// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/retr0h/agentpack/pkg/update (interfaces: RegistryLoader)
//
// Generated by this command:
//
//	mockgen -destination=registry_loader.gen.go -package=mocks github.com/retr0h/agentpack/pkg/update RegistryLoader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	registry "github.com/retr0h/agentpack/pkg/registry"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistryLoader is a mock of RegistryLoader interface.
type MockRegistryLoader struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryLoaderMockRecorder
	isgomock struct{}
}

// MockRegistryLoaderMockRecorder is the mock recorder for MockRegistryLoader.
type MockRegistryLoaderMockRecorder struct {
	mock *MockRegistryLoader
}

// NewMockRegistryLoader creates a new mock instance.
func NewMockRegistryLoader(ctrl *gomock.Controller) *MockRegistryLoader {
	mock := &MockRegistryLoader{ctrl: ctrl}
	mock.recorder = &MockRegistryLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistryLoader) EXPECT() *MockRegistryLoaderMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockRegistryLoader) Load(name string) (*registry.PackageManifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", name)
	ret0, _ := ret[0].(*registry.PackageManifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockRegistryLoaderMockRecorder) Load(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockRegistryLoader)(nil).Load), name)
}
