// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/retr0h/agentpack/internal/sync (interfaces: Installer)
//
// Generated by this command:
//
//	mockgen -destination=installer.gen.go -package=mocks github.com/retr0h/agentpack/internal/sync Installer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	install "github.com/retr0h/agentpack/internal/install"
	gomock "go.uber.org/mock/gomock"
)

// MockInstaller is a mock of Installer interface.
type MockInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockInstallerMockRecorder
	isgomock struct{}
}

// MockInstallerMockRecorder is the mock recorder for MockInstaller.
type MockInstallerMockRecorder struct {
	mock *MockInstaller
}

// NewMockInstaller creates a new mock instance.
func NewMockInstaller(ctrl *gomock.Controller) *MockInstaller {
	mock := &MockInstaller{ctrl: ctrl}
	mock.recorder = &MockInstallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstaller) EXPECT() *MockInstallerMockRecorder {
	return m.recorder
}

// Install mocks base method.
func (m *MockInstaller) Install(ctx context.Context, source string) (*install.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", ctx, source)
	ret0, _ := ret[0].(*install.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Install indicates an expected call of Install.
func (mr *MockInstallerMockRecorder) Install(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockInstaller)(nil).Install), ctx, source)
}
