---
name: Greetings

on: [pull_request, issues]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v3
      if: env.month != 'Oct'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for your first issue!'
        pr-message: 'Thank you for contributing to this project!'
    - uses: actions/first-interaction@v3
      if: env.month == 'Oct'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for your first issue! Happy Hacktoberfest!!!'
        pr-message: 'Thank you for contributing to this project. Happy Hacktoberfest!!!'
